### ISSUE TITLE
For all instances of the gold, rectangular button throughout the site, the hover state should go to #f5ae02 (slightly darker gold) instead of blue:

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/Sargon-QA#18]
https://drive.google.com/file/d/11jWeZGdh9ybgE4qtyXCApWplB3Jm5xuu/view?usp=sharing

This is not hovering to the correct color

**Comment by cmoosman1** [comment]
@pguevara65 - This is resolved in the current build

**Comment by pguevara65** [comment]
@NoelWormwood let me know if you want me to review

**Comment by NoelWormwood** [comment]
@jthiel16 Please review

**Comment by jthiel16** [comment]
@cmoosman1 I'm still seeing the issue. It's hovering to a brown, but should be just slightly darker than the original gold color: #f5ae02

**Comment by NoelWormwood** [comment]
@jthiel16 Can you QA here again?

**Comment by jthiel16** [comment]
Looks good, thank you
